storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '**':
    access: $all
    publish: $all
    proxy: npmjs
log: { type: file, path: proxy.log, level: debug }

web:
  enable: false
middlewares:
  audit:
    enabled: true
_debug: true
